apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    app: postgresql-client
spec:

  containers:
  - name: psql-client
    image: bitnami/postgresql:latest
    imagePullPolicy: Always
    stdin: true
    tty: true
    command: ["/bin/sh"] 
    envFrom:
      - secretRef:
          name: postgres
